version: "3.7"

services:

  api:
    build: ./api
    ports:
      - "8080-8090:8080"
    networks:
      - backend
    # deploy:
    #   mode: replicated
    #   replicas: 1
    # volumes:
    #   - /root/statping:/app

  dummy:
    build: ./dummy
    networks:
      - backend
  # apk --update add curl
  # apk add wrk
  # wrk -t12 -c400 -d30s http://api:8080/info

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
